/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

export type TransportType = 'daily' | 'smallwebrtc';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  'daily',
  'small_webrtc',
];

export const DEFAULT_TRANSPORT: TransportType = 'daily';

export const TRANSPORT_CONFIG: Record<TransportType, any> = {
  daily: { endpoint: '/api/start' },
  smallwebrtc: { webrtcUrl: '/api/offer' },
};
