/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

export type TransportType = "daily" | "smallwebrtc";

export const AVAILABLE_TRANSPORTS: TransportType[] = ["daily", "smallwebrtc"];

export const DEFAULT_TRANSPORT: TransportType = "daily";

// eslint-disable-next-line
export const TRANSPORT_CONFIG: Record<TransportType, any> = {
  daily: { endpoint: "/api/start" },
  smallwebrtc: { webrtcUrl: "/api/offer" },
};

// Presence service configuration
export const PRESENCE_WS_URL = process.env.NEXT_PUBLIC_PRESENCE_WS_URL || "ws://localhost:8765/ws";
