[project]
name = "presence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.104.0",
    "loguru>=0.7.0",
    "opencv-python>=4.8.0",
    "uvicorn[standard]>=0.24.0",
    "websockets>=12.0",
]
