[project]
name = "squobertos"
version = "0.1.0"
description = "SquobertOS - A TUI interface for Squobert"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "textual>=0.47.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
