name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get date
      id: date
      run: echo "date=$(date +'%F')" >> $GITHUB_OUTPUT
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64
        context: ./bot
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.date.outputs.date }}
    
    - name: Deploy to Pipecat Cloud
      run: |
        curl -X POST https://api.pipecat.daily.co/v1/agents/${{ github.event.repository.name }} \
          -H "Authorization: Bearer ${{ secrets.PCC_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "image": "${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest",
            "imagePullSecretSet": "cb-pluot-image-pull-secret",
            "secretSet": "squobert-secrets",
            "enableKrisp": true,
            "autoScaling": {
              "minAgents": 0,
              "maxAgents": 10
            }
          }'