name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bot

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get date
      id: date
      run: echo "date=$(date +'%F')" >> $GITHUB_OUTPUT
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.date.outputs.date }}
    
    - name: Install pipecatcloud
      run: pip install pipecatcloud
    
    - name: Deploy to Pipecat Cloud
      env:
        PIPECAT_API_KEY: ${{ secrets.PCC_API_KEY }}
      run: |
        pcc deploy -f